### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by mominrazaa** [harshavkumar/word_segmentation#1]
hey hope you are good brother  i got error in page.py line 68
![image](https://user-images.githubusercontent.com/60484757/75090731-bee75900-5587-11ea-8159-e483610a251c.png)

error is blow  
 im2, contours, hierarchy = cv2.findContours(edges, cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

I'm  using 
python  3.6 

help me please

**Comment by mominrazaa** [comment]
i solve the issue  and got that out put but i want to crop the images word by word as in sugmented folder but there is not sugmented images of my new input please help 
![image](https://user-images.githubusercontent.com/60484757/75091021-be9c8d00-558a-11ea-9098-268aab7218d1.png)

**Comment by mominrazaa** [comment]
Thank you very much you made my day

**Comment by dasbipro** [comment]
> Thank you very much you made my day

do you get the solve?

**Comment by mominrazashahid** [comment]
Yes, basically i was working on hand writer ln text recognition system so I combine your code with simple htr master and simple htr only recognized single word only so i combine both code first i segmented the words and then apply loop on recognizing text so i able to develop simple A4 paper yo hand writilten text recognition system.
